[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run build && npx serve -s build -l 3000"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NPM_CONFIG_LEGACY_PEER_DEPS = "true"
