[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run serve"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.args]
NPM_CONFIG_LEGACY_PEER_DEPS = "1"

[build.commands]
build = "npm run build"

[deploy.public]
directory = "build"
