services:
  - type: web
    name: livpulse-backend
    runtime: node
    plan: free  
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production