[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm install && npm run build && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production"
PORT = "8000"